{
 "title": "OSD Overview",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_osd_metadata, cluster)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(ceph_osd_metadata{}, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "OSD Read Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg (\n  rate(ceph_osd_op_r_latency_sum{job=~\"$job\"}[$__rate_interval]) /\n    on (ceph_daemon) rate(ceph_osd_op_r_latency_count{job=~\"$job\"}[$__rate_interval]) * 1000\n)\n",
     "legendFormat": "AVG read"
    },
    {
     "expr": "max(\n  rate(ceph_osd_op_r_latency_sum{job=~\"$job\"}[$__rate_interval]) /\n  on (ceph_daemon) rate(ceph_osd_op_r_latency_count{job=~\"$job\"}[$__rate_interval]) * 1000\n)\n",
     "legendFormat": "MAX read"
    },
    {
     "expr": "quantile(0.95,\n  (\n    rate(ceph_osd_op_r_latency_sum{job=~\"$job\"}[$__rate_interval]) /\n      on (ceph_daemon) rate(ceph_osd_op_r_latency_count{job=~\"$job\"}[$__rate_interval])\n      * 1000\n  )\n)\n",
     "legendFormat": "@95%ile"
    }
   ]
  },
  {
   "title": "Highest READ Latencies",
   "type": "table",
   "description": "This table shows the osd's that are delivering the 10 highest read latencies within the cluster",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,\n  (sort(\n    (\n      rate(ceph_osd_op_r_latency_sum{job=~\"$job\"}[$__rate_interval]) /\n        on (ceph_daemon) rate(ceph_osd_op_r_latency_count{job=~\"$job\"}[$__rate_interval]) *\n        1000\n    )\n  ))\n)\n"
    }
   ]
  },
  {
   "title": "OSD Write Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(\n  rate(ceph_osd_op_w_latency_sum{job=~\"$job\"}[$__rate_interval]) /\n    on (ceph_daemon) rate(ceph_osd_op_w_latency_count{job=~\"$job\"}[$__rate_interval])\n    * 1000\n)\n",
     "legendFormat": "AVG write"
    },
    {
     "expr": "max(\n  rate(ceph_osd_op_w_latency_sum{job=~\"$job\"}[$__rate_interval]) /\n    on (ceph_daemon) rate(ceph_osd_op_w_latency_count{job=~\"$job\"}[$__rate_interval]) *\n    1000\n)\n",
     "legendFormat": "MAX write"
    },
    {
     "expr": "quantile(0.95, (\n  rate(ceph_osd_op_w_latency_sum{job=~\"$job\"}[$__rate_interval]) /\n    on (ceph_daemon) rate(ceph_osd_op_w_latency_count{job=~\"$job\"}[$__rate_interval]) *\n    1000\n))\n",
     "legendFormat": "@95%ile write"
    }
   ]
  },
  {
   "title": "Highest WRITE Latencies",
   "type": "table",
   "description": "This table shows the osd's that are delivering the 10 highest write latencies within the cluster",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,\n  (sort(\n    (rate(ceph_osd_op_w_latency_sum{job=~\"$job\"}[$__rate_interval]) /\n      on (ceph_daemon) rate(ceph_osd_op_w_latency_count{job=~\"$job\"}[$__rate_interval]) *\n      1000)\n  ))\n)\n"
    }
   ]
  },
  {
   "title": "OSD Types Summary",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (device_class) (ceph_osd_metadata{job=~\"$job\"})",
     "legendFormat": "{{device_class}}"
    }
   ]
  },
  {
   "title": "OSD Objectstore Types",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_bluefs_wal_total_bytes{job=~\"$job\"})",
     "legendFormat": "bluestore"
    },
    {
     "expr": "absent(ceph_bluefs_wal_total_bytes{job=~\"$job\"}) * count(ceph_osd_metadata{job=~\"$job\"})",
     "legendFormat": "filestore"
    }
   ]
  },
  {
   "title": "OSD Size Summary",
   "type": "grafana-piechart-panel",
   "description": "The pie chart shows the various OSD sizes used within the cluster",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ceph_osd_stat_bytes{job=~\"$job\"} < 1099511627776)",
     "legendFormat": "<1TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{job=~\"$job\"} >= 1099511627776 < 2199023255552)",
     "legendFormat": "<2TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{job=~\"$job\"} >= 2199023255552 < 3298534883328)",
     "legendFormat": "<3TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{job=~\"$job\"} >= 3298534883328 < 4398046511104)",
     "legendFormat": "<4TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{job=~\"$job\"} >= 4398046511104 < 6597069766656)",
     "legendFormat": "<6TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{job=~\"$job\"} >= 6597069766656 < 8796093022208)",
     "legendFormat": "<8TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{job=~\"$job\"} >= 8796093022208 < 10995116277760)",
     "legendFormat": "<10TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{job=~\"$job\"} >= 10995116277760 < 13194139533312)",
     "legendFormat": "<12TB"
    },
    {
     "expr": "count(ceph_osd_stat_bytes{job=~\"$job\"} >= 13194139533312)",
     "legendFormat": "<12TB+"
    }
   ]
  },
  {
   "title": "Distribution of PGs per OSD",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "# of OSDs" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_numpg{job=~\"$job\"}",
     "legendFormat": "PGs per OSD"
    }
   ]
  },
  {
   "title": "OSD onode Hits Ratio",
   "type": "singlestat",
   "description": "This gauge panel shows onode Hits ratio to help determine if increasing RAM per OSD could help improve the performance of the cluster",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_bluestore_onode_hits{job=~\"$job\"}) / (\n  sum(ceph_bluestore_onode_hits{job=~\"$job\"}) +\n  sum(ceph_bluestore_onode_misses{job=~\"$job\"})\n)\n"
    }
   ]
  },
  { "title": "R/W Profile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Read/Write Profile",
   "type": "graph",
   "description": "Show the read/write workload profile overtime",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(ceph_pool_rd{job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "Reads"
    },
    {
     "expr": "round(sum(rate(ceph_pool_wr{job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Top Slow Ops",
   "type": "table",
   "description": "This table shows the 10 OSDs with the highest number of slow ops",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "topk(10,\n  (ceph_daemon_health_metrics{type=\"SLOW_OPS\", ceph_daemon=~\"osd.*\"})\n)\n"
    }
   ]
  }
 ]
}