---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy-redis
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      oauth2-proxy-redis:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 7.4.3@sha256:7df1eeff67eb0ba84f6b9d2940765a6bb1158081426745c185a03b1507de6a09

            env:
              REDIS_REPLICATION_MODE: master

            envFrom:
              - secretRef:
                  name: oauth2-proxy-redis-secrets

            resources:
              requests:
                cpu: 100m
              limits:
                memory: 1Gi

    service:
      app:
        controller: oauth2-proxy-redis
        ports:
          redis:
            enabled: true
            port: 6379
